
# Check Enable list
CHECKENABLE_SIGMA_FINAL_RANGE           = 0
CHECKENABLE_SIGNAL_RATE_FINAL_RANGE     = 1
CHECKENABLE_SIGNAL_REF_CLIP             = 2
CHECKENABLE_RANGE_IGNORE_THRESHOLD      = 3
CHECKENABLE_SIGNAL_RATE_MSRC            = 4
CHECKENABLE_SIGNAL_RATE_PRE_RANGE       = 5
CHECKENABLE_NUMBER_OF_CHECKS            = 6